// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2S9nLmGKCOMyixZ6Dk4yv9GkURHmOQOk',
    appId: '1:325132982536:web:753f215e58cc0c641cb4bd',
    messagingSenderId: '325132982536',
    projectId: 'grocery-app-e69ff',
    authDomain: 'grocery-app-e69ff.firebaseapp.com',
    storageBucket: 'grocery-app-e69ff.firebasestorage.app',
    measurementId: 'G-XBPTPYG501',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdSA0_zINeHOgDAAH9eUQHWFFtw6Aztwo',
    appId: '1:325132982536:android:bb6c47b1f0f9c82a1cb4bd',
    messagingSenderId: '325132982536',
    projectId: 'grocery-app-e69ff',
    storageBucket: 'grocery-app-e69ff.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2S9nLmGKCOMyixZ6Dk4yv9GkURHmOQOk',
    appId: '1:325132982536:web:810f28ebe6768f3a1cb4bd',
    messagingSenderId: '325132982536',
    projectId: 'grocery-app-e69ff',
    authDomain: 'grocery-app-e69ff.firebaseapp.com',
    storageBucket: 'grocery-app-e69ff.firebasestorage.app',
    measurementId: 'G-0ZXRG28NYS',
  );
}
